---
micronaut:
  server:
    port: 9000
  application:
    name: gateway

---
hystrix:
  stream:
    enabled: false

---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
